spring:
    profiles:
        active: local
    kafka:
        bootstrap-servers: docker-kafka:9092
eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka
andrew:
    thing: hello me
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: refresh,hystrix.stream,health,info