spring:
  kafka:
    bootstrap-servers:
      - docker-kafka:9092
  profiles:
    active: local
server:
  port: 8080

kafka:
    topic:
        refresh: refresh-config

---

spring:
  profiles:
    active: dev